// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetserver.Data;

#nullable disable

namespace aspnetserver.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("aspnetserver.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Contact = "000-0001",
                            Email = "database1@email.com",
                            Name = "Post 1"
                        },
                        new
                        {
                            PostId = 2,
                            Contact = "000-0002",
                            Email = "database2@email.com",
                            Name = "Post 2"
                        },
                        new
                        {
                            PostId = 3,
                            Contact = "000-0003",
                            Email = "database3@email.com",
                            Name = "Post 3"
                        },
                        new
                        {
                            PostId = 4,
                            Contact = "000-0004",
                            Email = "database4@email.com",
                            Name = "Post 4"
                        },
                        new
                        {
                            PostId = 5,
                            Contact = "000-0005",
                            Email = "database5@email.com",
                            Name = "Post 5"
                        },
                        new
                        {
                            PostId = 6,
                            Contact = "000-0006",
                            Email = "database6@email.com",
                            Name = "Post 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
